// 100 Indian cities
export const city = [
  { id: 1, cityName: 'Mumbai' },
  { id: 2, cityName: 'Delhi' },
  { id: 3, cityName: 'Bengaluru' },
  { id: 4, cityName: 'Hyderabad' },
  { id: 5, cityName: 'Ahmedabad' },
  { id: 6, cityName: 'Chennai' },
  { id: 7, cityName: 'Kolkata' },
  { id: 8, cityName: 'Pune' },
  { id: 9, cityName: 'Jaipur' },
  { id: 10, cityName: 'Surat' },
  { id: 11, cityName: 'Lucknow' },
  { id: 12, cityName: 'Kanpur' },
  { id: 13, cityName: 'Nagpur' },
  { id: 14, cityName: 'Indore' },
  { id: 15, cityName: 'Thane' },
  { id: 16, cityName: 'Bhopal' },
  { id: 17, cityName: 'Visakhapatnam' },
  { id: 18, cityName: 'Patna' },
  { id: 19, cityName: 'Vadodara' },
  { id: 20, cityName: 'Ghaziabad' },
  { id: 21, cityName: 'Ludhiana' },
  { id: 22, cityName: 'Agra' },
  { id: 23, cityName: 'Nashik' },
  { id: 24, cityName: 'Faridabad' },
  { id: 25, cityName: 'Meerut' },
  { id: 26, cityName: 'Rajkot' },
  { id: 27, cityName: 'Kalyan-Dombivli' },
  { id: 28, cityName: 'Vasai-Virar' },
  { id: 29, cityName: 'Varanasi' },
  { id: 30, cityName: 'Srinagar' },
  { id: 31, cityName: 'Aurangabad' },
  { id: 32, cityName: 'Dhanbad' },
  { id: 33, cityName: 'Amritsar' },
  { id: 34, cityName: 'Navi Mumbai' },
  { id: 35, cityName: 'Allahabad (Prayagraj)' },
  { id: 36, cityName: 'Ranchi' },
  { id: 37, cityName: 'Howrah' },
  { id: 38, cityName: 'Coimbatore' },
  { id: 39, cityName: 'Jabalpur' },
  { id: 40, cityName: 'Gwalior' },
  { id: 41, cityName: 'Vijayawada' },
  { id: 42, cityName: 'Jodhpur' },
  { id: 43, cityName: 'Madurai' },
  { id: 44, cityName: 'Raipur' },
  { id: 45, cityName: 'Kota' },
  { id: 46, cityName: 'Guwahati' },
  { id: 47, cityName: 'Chandigarh' },
  { id: 48, cityName: 'Solapur' },
  { id: 49, cityName: 'Hubli-Dharwad' },
  { id: 50, cityName: 'Bareilly' },
  { id: 51, cityName: 'Moradabad' },
  { id: 52, cityName: 'Mysuru' },
  { id: 53, cityName: 'Gurgaon' },
  { id: 54, cityName: 'Aligarh' },
  { id: 55, cityName: 'Jalandhar' },
  { id: 56, cityName: 'Tiruchirappalli' },
  { id: 57, cityName: 'Bhubaneswar' },
  { id: 58, cityName: 'Salem' },
  { id: 59, cityName: 'Warangal' },
  { id: 60, cityName: 'Mira-Bhayandar' },
  { id: 61, cityName: 'Thiruvananthapuram' },
  { id: 62, cityName: 'Bhiwandi' },
  { id: 63, cityName: 'Saharanpur' },
  { id: 64, cityName: 'Gorakhpur' },
  { id: 65, cityName: 'Guntur' },
  { id: 66, cityName: 'Bikaner' },
  { id: 67, cityName: 'Amravati' },
  { id: 68, cityName: 'Noida' },
  { id: 69, cityName: 'Jamshedpur' },
  { id: 70, cityName: 'Bhilai' },
  { id: 71, cityName: 'Cuttack' },
  { id: 72, cityName: 'Firozabad' },
  { id: 73, cityName: 'Kochi' },
  { id: 74, cityName: 'Dehradun' },
  { id: 75, cityName: 'Durgapur' },
  { id: 76, cityName: 'Ajmer' },
  { id: 77, cityName: 'Siliguri' },
  { id: 78, cityName: 'Ujjain' },
  { id: 79, cityName: 'Jhansi' },
  { id: 80, cityName: 'Ulhasnagar' },
  { id: 81, cityName: 'Jammu' },
  { id: 82, cityName: 'Sangli' },
  { id: 83, cityName: 'Belgaum' },
  { id: 84, cityName: 'Mangalore' },
  { id: 85, cityName: 'Tirunelveli' },
  { id: 86, cityName: 'Malegaon' },
  { id: 87, cityName: 'Gaya' },
  { id: 88, cityName: 'Tiruppur' },
  { id: 89, cityName: 'Davanagere' },
  { id: 90, cityName: 'Kozhikode' },
  { id: 91, cityName: 'Akola' },
  { id: 92, cityName: 'Kurnool' },
  { id: 93, cityName: 'Bokaro' },
  { id: 94, cityName: 'Rajahmundry' },
  { id: 95, cityName: 'Ballari' },
  { id: 96, cityName: 'Agartala' },
  { id: 97, cityName: 'Bhavnagar' },
  { id: 98, cityName: 'Muzaffarpur' },
  { id: 99, cityName: 'Ahmednagar' },
  { id: 100, cityName: 'Kolhapur' },
];

// 29 Indian states
export const states = [
  { id: 1, stateName: 'Andhra Pradesh' },
  { id: 2, stateName: 'Arunachal Pradesh' },
  { id: 3, stateName: 'Assam' },
  { id: 4, stateName: 'Bihar' },
  { id: 5, stateName: 'Chhattisgarh' },
  { id: 6, stateName: 'Goa' },
  { id: 7, stateName: 'Gujarat' },
  { id: 8, stateName: 'Haryana' },
  { id: 9, stateName: 'Himachal Pradesh' },
  { id: 10, stateName: 'Jharkhand' },
  { id: 11, stateName: 'Karnataka' },
  { id: 12, stateName: 'Kerala' },
  { id: 13, stateName: 'Madhya Pradesh' },
  { id: 14, stateName: 'Maharashtra' },
  { id: 15, stateName: 'Manipur' },
  { id: 16, stateName: 'Meghalaya' },
  { id: 17, stateName: 'Mizoram' },
  { id: 18, stateName: 'Nagaland' },
  { id: 19, stateName: 'Odisha' },
  { id: 20, stateName: 'Punjab' },
  { id: 21, stateName: 'Rajasthan' },
  { id: 22, stateName: 'Sikkim' },
  { id: 23, stateName: 'Tamil Nadu' },
  { id: 24, stateName: 'Telangana' },
  { id: 25, stateName: 'Tripura' },
  { id: 26, stateName: 'Uttar Pradesh' },
  { id: 27, stateName: 'Uttarakhand' },
  { id: 28, stateName: 'West Bengal' },
  { id: 29, stateName: 'Jammu and Kashmir' },
];

export const Gender = [
  {
    id: 1,
    label: 'Male',
  },
  {
    id: 2,
    label: 'Female',
  },
  {
    id: 3,
    label: 'Others',
  },
];
